from datetime import datetime, timedelta
import json
import requests
import os
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.hooks.base import BaseHook

default_args = {
    'owner': 'inventory-team',
    'start_date': datetime(2024, 1, 1),
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'reorder_automation',
    default_args=default_args,
    description='Automated reordering based on inventory levels',
    schedule_interval=timedelta(hours=6),
    catchup=False,
    tags=['inventory', 'automation'],
)

# Configuration
INVENTORY_SERVICE_URL = os.getenv('INVENTORY_SERVICE_URL', 'http://inventory-service:8080')
REORDER_SERVICE_URL = os.getenv('REORDER_SERVICE_URL', 'http://reorder-service:8081')
API_KEY = os.getenv('SERVICE_API_KEY', 'default-key')

def get_auth_headers():
    return {
        'Content-Type': 'application/json',
        'X-API-KEY': API_KEY
    }

def check_low_stock(**context):
    """
    Check for low stock items via Inventory Service API.
    Push list of items needing reorder to XCom.
    """
    print("Checking for low stock items...")
    try:
        response = requests.get(
            f"{INVENTORY_SERVICE_URL}/api/v1/inventory/low-stock/reorder-needed",
            headers=get_auth_headers(),
            timeout=10
        )
        response.raise_for_status()
        
        items = response.json()
        print(f"Found {len(items)} items needing reorder")
        
        # Log items for visibility
        for item in items:
            print(f"Low stock: SKU={item.get('sku')}, Qty={item.get('quantityOnHand')}, ReorderPoint={item.get('reorderPoint')}")
            
        return items
    except Exception as e:
        print(f"Error checking low stock: {str(e)}")
        raise

def generate_orders(**context):
    """
    Generate purchase orders for items identified in the previous step.
    Pull items from XCom.
    """
    print("Generating purchase orders...")
    try:
        # Pull items from the previous task
        ti = context['ti']
        items_needing_reorder = ti.xcom_pull(task_ids='check_low_stock')
        
        if not items_needing_reorder:
            print("No items need reordering. Skipping order generation.")
            return "No orders generated"
            
        orders_created = 0
        
        for item in items_needing_reorder:
            sku = item.get('sku')
            warehouse_id = item.get('warehouseId')
            # Default reorder quantity or calculated amount
            quantity = item.get('reorderQuantity', 100)
            
            payload = {
                'sku': sku,
                'warehouseId': warehouse_id,
                'quantity': quantity,
                'autoGenerated': True,
                'reason': 'Low stock automation'
            }
            
            # Call Reorder Service to create order
            # Note: Assuming reorder-service has this endpoint
            response = requests.post(
                f"{REORDER_SERVICE_URL}/api/v1/orders",
                json=payload,
                headers=get_auth_headers(),
                timeout=10
            )
            
            if response.status_code in (200, 201):
                print(f"Created order for {sku}: {response.json().get('orderId', 'unknown')}")
                orders_created += 1
            else:
                print(f"Failed to create order for {sku}: {response.text}")
                
        return f"Generated {orders_created} purchase orders"
        
    except Exception as e:
        print(f"Error generating orders: {str(e)}")
        raise

check_task = PythonOperator(
    task_id='check_low_stock',
    python_callable=check_low_stock,
    provide_context=True,
    dag=dag,
)

generate_task = PythonOperator(
    task_id='generate_orders',
    python_callable=generate_orders,
    provide_context=True,
    dag=dag,
)

check_task >> generate_task
