package com.reorder.controller;

import com.reorder.dto.CreateOrderRequest;
import com.reorder.model.PurchaseOrder;
import com.reorder.model.ReorderRecommendation;
import com.reorder.service.PurchaseOrderGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDateTime;

@RestController
@RequestMapping("/api/v1/orders")
public class PurchaseOrderController {

    @Autowired
    private PurchaseOrderGenerator purchaseOrderGenerator;

    @PostMapping
    public ResponseEntity<PurchaseOrder> createOrder(@RequestBody CreateOrderRequest request) {
        ReorderRecommendation recommendation = new ReorderRecommendation();
        recommendation.setSku(request.getSku());
        recommendation.setWarehouseId(request.getWarehouseId());
        recommendation.setCurrentQuantity(0);
        recommendation.setReorderPoint(0);
        recommendation.setRecommendedQuantity(request.getQuantity());
        recommendation.setPriority(Boolean.TRUE.equals(request.getAutoGenerated()) ? "HIGH" : "MEDIUM");
        recommendation.setRecommendedDate(LocalDateTime.now());

        PurchaseOrder order = purchaseOrderGenerator.generateOrder(recommendation);
        return ResponseEntity.status(HttpStatus.CREATED).body(order);
    }
}
